version: '2'
services:
  efinix_sapphire_zephyr_app:
    image: zephyr:efinix_test
    container_name: zephyr_efinix_sapphire
    privileged: true
    user: "1000:1000"

    volumes:
      - efinix_zephyr_sapphire:/app/zephyrrtos:ro
      - zephyr:/zephyr:rw
    command: bash -c "/app/zephyrrtos/inits_scripts/inital_setup.sh ;  tail -f /dev/null"
    stdin_open: true
    tty: true

volumes:
  efinix_zephyr_sapphire:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ./volume
  zephyr:
