version: '1'
services:
  efinix_sapphire_zephyr_app:
    image: zephyr:efinix_test
    container_name: zephyr_efinix_sapphire
    privileged: true
    volumes:
      - efinix_zephyr_sapphire:/app/zephyrrtos
    stdin_open: true
    tty: true
    command: sh -c "/app/zephyrrtos/inits_scripts/inital_setup.sh  && tail -f /dev/null"

volumes:
  efinix_zephyr_sapphire:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ./volume